# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
   
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      
      - name: Set up environment variables
        run: |
          echo "PORT=${{ env.PORT }}" >> .env
          echo "MONGODB_CONNECTION_STRING=${{ env.MONGODB_CONNECTION_STRING }}" >> .env    
          echo "SECRET_KEY=${{ env.SECRET_KEY }}" >> .env
          echo "EMAIL=${{ env.EMAIL }}" >> .env
          echo "EMAIL_PASSWORD=${{ env.EMAIL_PASSWORD }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ env.JWT_REFRESH_SECRET }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ env.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ env.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ env.CLOUDINARY_API_SECRET }}" >> .env
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_BUCKET_NAME=${{ env.AWS_BUCKET_NAME }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ env.STRIPE_SECRET_KEY }}" >> .env
          echo "CURRENCY=${{ env.CURRENCY }}" >> .env
          echo "SUCCESS_URL=${{ env.SUCCESS_URL }}" >> .env
          echo "CANCEL_URL=${{ env.CANCEL_URL }}" >> .env
          
      - name: Verify Environment Variables
        run: node verify-env.js
        
      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build --if-present
        
      - name: Start Application
        run: pm2 restart init
          